exports.config = {
  user: process.env.TB_KEY,
  key: process.env.TB_SECRET,
  specs: ['./specs/**/*.js'],
  exclude: [],
  maxInstances: 10,
  capabilities: [{
    maxInstances: 5,
    browserName: 'firefox',
  }],
  sync: true,
  logLevel: 'silent',
  coloredLogs: true,
  screenshotPath: './error-screenshots/',
  baseUrl: 'http://localhost',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  services: ['testingbot'],
  framework: 'mocha',
  reporters: ['allure', 'json'],
  mochaOpts: {ui: 'bdd'},
}
